### ISSUE TITLE
Missing documentation on "SKYSS_MOBILE_API_URL"

### ISSUE THREAD

**Issue by thomas-alrek** [Starefossen/node-skyss#1]
It should be documentet how to get the "SKYSS_MOBILE_API_URL" parameter. I can't seem to find it, and therefore isn't able to run the package.

**Comment by Starefossen** [comment]
You need to [contact Skyss](https://www.skyss.no/en/kontakt-oss/contact-form/) in order to obtain access to their API (API url and authentication).

**Comment by thomas-alrek** [comment]
Ah, okay, thank you. Do you know if the API is free to use, or do Skyss require a subscription to access the API?

**Comment by Starefossen** [comment]
The API is free to use (eg. no subscription or payment) as far as I know of – as long as you are within reasonable usage limits :smile:

**Comment by thomas-alrek** [comment]
Great, thank you for your help :)
